CREATE ROLE ccdb NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
CREATE ROLE ccdbuser NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD '123Next';
GRANT ccdb TO ccdbuser;
CREATE DATABASE ccdb
WITH
    CONNECTION LIMIT = -1;
REVOKE ALL ON DATABASE ccdb FROM public;
ALTER DATABASE ccdb OWNER TO ccdbuser;
